#ifndef VERSIONS_H_
#define VERSIONS_H_

/* FIRMWARE VERSION */
#define VER_FW_MAJOR 0x01
#define VER_FW_MINOR 0x04
#define VER_FW_PATCH 0x00

/* ADAPTER PROTOCOL VERSION */
#define VER_AP_MAJOR 0x02
#define VER_AP_MINOR 0x00
#define VER_AP_PATCH 0x00

#endif /* VERSIONS_H_ */
